openapi: 3.0.0
info:
  title: escrows
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /profiles:
    post:
      summary: Create Profile
      operationId: post-profiles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                profileId:
                  type: string
                  description: Merchant id in client system
                countryOfOrigin:
                  type: string
                  description: "Merchant's country of origin"
                  enum:
                    - US
                    - CN
                type:
                  type: string
                  description: Profile type
                  enum:
                    - INDIVIDUAL
                    - CORPORATION
                emial:
                  type: string
                  format: email
                  description: Merchant email address
                kyc:
                  type:
                    - string
                    - object
                  required:
                    - entityName
                    - entityType
                    - registryNumber
                    - regCertificateCopy
                    - legalRep
                  properties:
                    entityName:
                      type: string
                      description: Company name in English
                    entityType:
                      type: string
                      description: Business type
                    registryNumber:
                      type: string
                      description: Company number
                    regCertificateCopy:
                      type: string
                      description: Company liscens document name
                    legalRep:
                      type: object
                      required:
                        - name
                        - idNumber
                        - idFrontImg
                      properties:
                        name:
                          type: string
                          description: Legal Representative’s name in English
                        idNumber:
                          type: string
                          description: Legal Representative’s id number
                        idFrontImg:
                          type: string
                          description: Legal Representative’s id front document name
                        idBackImg:
                          type: string
                          description: Legal Representative’s id back document name. Optional if id type is passport
              required:
                - profileId
                - countryOfOrigin
                - type
                - emial
                - kyc
        description: ''
      description: Create an Avalara Fiscal Rep merchant profile in Lianlian Pay system
  '/profiles/{profileId}':
    parameters:
      - schema:
          type: string
        name: profileId
        in: path
        required: true
    get:
      summary: Get Profile By ID
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
      operationId: get-profiles-profileId
      description: Get a single profile details by profile id
  '/profiles/{profileId}/bills':
    parameters:
      - schema:
          type: string
        name: profileId
        in: path
        required: true
    post:
      summary: Create Bill
      operationId: post-profiles-profileId-bills
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Unique obligation bill id generated by client
                region:
                  type: string
                  description: Bill region/jurisdiction
                currency:
                  type: string
                  description: Bill currency
                amount:
                  type: string
                  description: Bill amount
                period:
                  type: string
                  description: Bill period
                dueDate:
                  type: string
                  description: Bill due date
                expireDate:
                  type: string
                  description: Bill expire date
                accountNo:
                  type: string
                  description: Payee account number
                accountName:
                  type: string
                  description: Payee account name
                bankName:
                  type: string
                  description: Payee bank name
                branchCode:
                  type: string
                  description: Payee branch code
                swift:
                  type: string
                  description: SWIFT
                rfb:
                  type: string
                memo:
                  type: string
              required:
                - id
                - region
                - currency
                - amount
                - period
                - dueDate
                - expireDate
                - accountNo
                - accountName
                - bankName
                - branchCode
                - swift
                - rfb
        description: ''
      description: Create a bill obligation for a profile
  '/bills/{billId}':
    parameters:
      - schema:
          type: string
        name: billId
        in: path
        required: true
    get:
      summary: Get Bill By ID
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
      operationId: get-profiles-profileId-bills-billId
      description: Get a bill details by its id
  '/bills/{billId}/submit':
    parameters:
      - schema:
          type: string
        name: billId
        in: path
        required: true
    put:
      summary: Submit Bill
      operationId: put-bills-billId-submit
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
      description: Submit a single bill
  '/bills/{billId}/void':
    parameters:
      - schema:
          type: string
        name: billId
        in: path
        required: true
    put:
      summary: Void Bill
      operationId: put-bills-billId-void
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
      description: Void a single bill
  '/profiles/{profileId}/accounts':
    parameters:
      - schema:
          type: string
        name: profileId
        in: path
        required: true
    post:
      summary: Create Account
      operationId: post-profiles-profileId-accounts
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                region:
                  type: string
                  description: Account region
                currency:
                  type: string
                  description: Account currency
              required:
                - region
                - currency
        description: ''
      description: Create an account for a profile
  '/accounts/{accountId}':
    parameters:
      - schema:
          type: string
        name: accountId
        in: path
        required: true
    get:
      summary: Get Account By ID
      tags: []
      responses: {}
      operationId: get-accounts-accountId
      description: Get a single account details by its account id.
components:
  schemas:
    Profile:
      title: Profile
      type: object
      description: ''
      properties:
        id:
          type: string
          description: Merchant id in client system
        countryOfOrigin:
          type: string
          description: "Merchant's country of origin"
        type:
          type: string
          description: Merchant type
          enum:
            - INDIVIDUAL
            - COMPANY
        kyc:
          $ref: '#/components/schemas/CN-ENTITY-KYC'
      required:
        - id
        - countryOfOrigin
        - type
        - kyc
    Bill:
      title: Bill
      type: object
      description: ''
      properties:
        id:
          type: string
          description: bill(obligation) id in client system
        region:
          type: string
          description: bill(obligation) region
        currency:
          type: string
          description: bill(obligation) currency
        amount:
          type: string
          description: bill(obligation) amount
        period:
          type: string
          description: bill(obligation) period
        dueDate:
          type: string
          description: bill(obligation) due date
          format: date
          example: 'YYYY-MM-DD, e.g. 2010-01-21'
        expireDate:
          type: string
          description: bill(obligation) expire date
          format: date
          example: 'YYYY-MM-DD, e.g. 2010-01-21'
        payee:
          $ref: '#/components/schemas/Account-Info'
        createTime:
          type: string
          format: date-time
          example: 'UTC timestamp, e.g. 2019-01-01T00:00:000Z'
          description: Bill created time
        modifyTime:
          type: string
          format: date-time
          example: 'UTC timestamp, e.g. 2019-01-01T00:00:000Z'
          description: Bill last modified time
        fundingTime:
          type: string
          format: date-time
          example: 'UTC timestamp, e.g. 2019-01-01T00:00:000Z'
          description: Bill funded time
        fundingStatus:
          type: string
          description: Funding status
        paymentTime:
          type: string
          format: date-time
          example: 'UTC timestamp, e.g. 2019-01-01T00:00:000Z'
          description: Bill payment time
        paymentStatus:
          type: string
          description: Funding status
      required:
        - id
        - region
        - currency
        - amount
        - period
        - dueDate
        - expireDate
        - payee
        - fundingStatus
        - paymentStatus
    Address:
      title: Address
      type: object
      properties:
        lineOne:
          type: string
          description: Address Line 1
        lineTwo:
          type: string
          description: Address Line 2
        city:
          type: string
          description: City/Town
        province:
          type: string
          description: Province/Region/State
        country:
          type: string
          description: Country
        postalCode:
          type: string
          description: Postal Code/Zip Code
      required:
        - lineOne
        - city
        - province
        - country
        - postalCode
    Account:
      title: Account
      type: object
      description: ''
      properties:
        balance:
          type: string
          description: Account balance in account currency
        currency:
          type: string
          description: Account currency
        details:
          $ref: '#/components/schemas/Account-Info'
        type:
          type: string
          enum:
            - PAYMENT
            - FUNDING
          description: 'Account type, PAYMENT/FUNDING'
        id:
          type: string
          description: Account id in Lianlina Pay system
      required:
        - balance
        - currency
        - type
        - id
    CN-ENTITY-KYC:
      title: CN ENTITY KYC
      type: object
      description: ''
      properties:
        entityName:
          type: string
          description: Company name in English
        entityType:
          type: string
          description: Business type. Enum
        registryNumber:
          type: string
          description: Company number
        regCertificateCopy:
          $ref: ''
        email:
          type: string
          description: Merchant email address
          format: email
        legalRep:
          $ref: '#/components/schemas/Legal-Representative'
        ubo:
          type: array
          description: 'Profile List<UBO> information '
          items:
            $ref: '#/components/schemas/UBO'
      required:
        - entityName
        - entityType
        - registryNumber
        - regCertificateCopy
    Legal-Representative:
      title: Legal-Representative
      type: object
      description: ''
      properties:
        name:
          type: string
        idType:
          type: string
        idNumber:
          type: string
        idFrontImg:
          $ref: '#/components/schemas/Document'
        idBackImg:
          $ref: '#/components/schemas/Document'
        idIssueDate:
          type: string
          format: date
          example: 'YYYY-MM-DD, e.g. 2010-01-21'
        idExpireDate:
          type: string
          format: date
          example: 'YYYY-MM-DD, e.g. 2010-01-21'
        nationality:
          type: string
        birthday:
          type: string
          format: date
          example: 'YYYY-MM-DD, e.g. 2010-01-21'
        mobile:
          type: string
        residentialAddress:
          $ref: '#/components/schemas/Address'
      required:
        - name
        - idNumber
        - idFrontImg
        - idBackImg
    UBO:
      title: UBO
      type: object
      properties:
        name:
          type: string
          description: UBO name in English
        idType:
          type: string
          description: 'ID type, ID-Card/Passport'
          enum:
            - IDCARD
            - PASSPORT
        idNumber:
          type: string
          description: UBO id number
        idFrontImg:
          $ref: '#/components/schemas/Document'
        idBackImg:
          $ref: '#/components/schemas/Document'
        idIssueDate:
          type: string
          description: UBO id issue date
          format: date
          example: 'YYYY-MM-DD, e.g. 2010-01-21'
        idExpireDate:
          type: string
          description: UBO id expiration date
          format: date
          example: 'YYYY-MM-DD, e.g. 2010-01-21'
        birthday:
          type: string
          format: date
          example: 'YYYY-MM-DD, e.g. 2010-01-21'
          description: UBO birthday
        residentialAddress:
          $ref: '#/components/schemas/Address'
        shareholdingRatio:
          type: string
          description: UBO share holding ratio
      required:
        - name
        - idNumber
        - idFrontImg
        - idBackImg
    Error:
      title: Error
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    Account-Info:
      title: Account-Info
      type: object
      description: ''
      properties:
        number:
          type: string
          description: Account number
        name:
          type: string
          description: Account name
        bankName:
          type: string
          description: Bank name
        branchCode:
          type: string
          description: Branch code
        swift:
          type: string
          description: Bank SWIFT code
        region:
          type: string
          description: 'Account region, two letter region code'
      required:
        - number
        - name
        - swift
        - region
    Document:
      title: Document
      type: object
      properties:
        name:
          type: string
          description: Document name
        size:
          type: string
          description: Document size
        createTime:
          type: string
          description: 'Document create time, UTC timestamp'
          format: date-time
          example: 'UTC timestamp, e.g. 2019-01-01T00:00:000Z'
      required:
        - name
