openapi: 3.0.0
info:
  title: escrows
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /profiles:
    post:
      summary: Create a profile
      operationId: post-profiles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                profileId:
                  type: string
                  description: Merchant id in client system
                countryOfOrigin:
                  type: string
                type:
                  type: string
                  description: Company type
                emial:
                  type: string
                kyc:
                  type:
                    - string
                    - object
                  required:
                    - entityName
                    - entityType
                    - registryNumber
                    - regCertificateCopy
                    - legalRep
                  properties:
                    entityName:
                      type: string
                      description: Company name in English
                    entityType:
                      type: string
                      description: Business type
                    registryNumber:
                      type: string
                      description: Company number
                    regCertificateCopy:
                      type: string
                    legalRep:
                      type: object
                      required:
                        - name
                        - idNumber
                        - idFrontImg
                      properties:
                        name:
                          type: string
                        idNumber:
                          type: string
                        idFrontImg:
                          type: string
                        idBackImg:
                          type: string
              required:
                - profileId
                - countryOfOrigin
                - type
                - emial
                - kyc
        description: ''
      description: Create an Avalara Fiscal Rep merchant profile in Lianlian Pay system
  '/profiles/{profileId}':
    parameters:
      - schema:
          type: string
        name: profileId
        in: path
        required: true
    get:
      summary: Get a single profile detailes by profile id
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
      operationId: get-profiles-profileId
  '/profiles/{profileId}/bills':
    parameters:
      - schema:
          type: string
        name: profileId
        in: path
        required: true
    post:
      summary: Create an obligation bill for a profile
      operationId: post-profiles-profileId-bills
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Unique obligation bill id generated by client
                region:
                  type: string
                  description: Bill region/jurisdiction
                currency:
                  type: string
                  description: Bill currency
                amount:
                  type: string
                  description: Bill amount
                period:
                  type: string
                  description: Bill period
                dueDate:
                  type: string
                  description: Bill due date
                expireDate:
                  type: string
                  description: Bill expire date
                accountNo:
                  type: string
                  description: Payee account number
                accountName:
                  type: string
                  description: Payee account name
                bankName:
                  type: string
                  description: Payee bank name
                branchCode:
                  type: string
                  description: Payee branch code
                swift:
                  type: string
                  description: SWIFT
                rfb:
                  type: string
                memo:
                  type: string
              required:
                - id
                - region
                - currency
                - amount
                - period
                - dueDate
                - expireDate
                - accountNo
                - accountName
                - bankName
                - branchCode
                - swift
                - rfb
        description: ''
  '/bills/{billId}':
    parameters:
      - schema:
          type: string
        name: billId
        in: path
        required: true
    get:
      summary: Get a single bill details by bill id
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
      operationId: get-profiles-profileId-bills-billId
  '/bills/{billId}/submit':
    parameters:
      - schema:
          type: string
        name: billId
        in: path
        required: true
    put:
      summary: Submit a single bill by id
      operationId: put-bills-billId-submit
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
  '/bills/{billId}/void':
    parameters:
      - schema:
          type: string
        name: billId
        in: path
        required: true
    put:
      summary: Void a single bill by id
      operationId: put-bills-billId-void
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
  '/profiles/{profileId}/accounts':
    parameters:
      - schema:
          type: string
        name: profileId
        in: path
        required: true
    post:
      summary: Create a single account for a profile
      operationId: post-profiles-profileId-accounts
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                region:
                  type: string
                  description: Account region
                currency:
                  type: string
                  description: Account currency
              required:
                - region
                - currency
        description: ''
  '/accounts/{accountId}':
    parameters:
      - schema:
          type: string
        name: accountId
        in: path
        required: true
    get:
      summary: Get a single account details by id
      tags: []
      responses: {}
      operationId: get-accounts-accountId
components:
  schemas:
    Profile:
      title: Profile
      type: object
      description: ''
      properties:
        id:
          type: string
          description: Merchant id in client system
        countryOfOrigin:
          type: string
          description: "Merchant's country of origin"
        type:
          type: string
          description: Merchant type
          enum:
            - INDIVIDUAL
            - COMPANY
        kyc:
          $ref: '#/components/schemas/CN-ENTITY-KYC'
      required:
        - id
        - countryOfOrigin
        - type
        - kyc
    Bill:
      title: Bill
      type: object
      description: ''
      properties:
        id:
          type: string
          description: bill(obligation) id in client system
        region:
          type: string
          description: bill(obligation) region
        currency:
          type: string
          description: bill(obligation) currency
        amount:
          type: string
          description: bill(obligation) amount
        period:
          type: string
          description: bill(obligation) period
        dueDate:
          type: string
          description: bill(obligation) due date
        expireDate:
          type: string
          description: bill(obligation) expire date
        payee:
          $ref: '#/components/schemas/Account-Info'
        createTime:
          type: string
        modifyTime:
          type: string
        fundingTime:
          type: string
        fundingStatus:
          type: string
        paymentTime:
          type: string
        paymentStatus:
          type: string
      required:
        - id
        - region
        - currency
        - amount
        - period
        - dueDate
        - expireDate
        - payee
        - fundingStatus
        - paymentStatus
    Address:
      title: Address
      type: object
      properties:
        lineOne:
          type: string
          description: Address Line 1
        lineTwo:
          type: string
          description: Address Line 2
        city:
          type: string
          description: City/Town
        province:
          type: string
          description: Province/Region/State
        country:
          type: string
          description: Country
        postalCode:
          type: string
          description: Postal Code/Zip Code
      required:
        - lineOne
        - city
        - province
        - country
        - postalCode
    Account:
      title: Account
      type: object
      description: ''
      properties:
        balance:
          type: string
          description: Account balance in account currency
        currency:
          type: string
          description: Account currency
        details:
          $ref: '#/components/schemas/Account-Info'
        type:
          type: string
          enum:
            - PAYMENT
            - FUNDING
          description: 'Account type, PAYMENT/FUNDING'
        id:
          type: string
          description: Account id in Lianlina Pay system
      required:
        - balance
        - currency
        - type
        - id
    CN-ENTITY-KYC:
      title: CN ENTITY KYC
      type: object
      description: ''
      properties:
        entityName:
          type: string
          description: Company name in English
        entityType:
          type: string
          description: Business type. Enum
        registryNumber:
          type: string
          description: Company number
        regCertificateCopy:
          $ref: ''
        email:
          type: string
        legalRep:
          $ref: '#/components/schemas/Legal-Representative'
        ubo:
          type: array
          items:
            $ref: '#/components/schemas/UBO'
      required:
        - entityName
        - entityType
        - registryNumber
        - regCertificateCopy
    Legal-Representative:
      title: Legal-Representative
      type: object
      properties:
        name:
          type: string
        idType:
          type: string
        idNumber:
          type: string
        idFrontImg:
          type: string
        idBackImg:
          type: string
        idIssueDate:
          type: string
        idExpireDate:
          type: string
        nationality:
          type: string
        birthday:
          type: string
        mobile:
          type: string
        residentialAddress:
          $ref: '#/components/schemas/Address'
      required:
        - name
        - idNumber
        - idFrontImg
        - idBackImg
    UBO:
      title: UBO
      type: object
      properties:
        name:
          type: string
        idType:
          type: string
          description: 'ID type, ID-Card/Passport'
          enum:
            - IDCARD
            - PASSPORT
        idNumber:
          type: string
        idFrontImg:
          type: string
        idBackImg:
          type: string
        idIssueDate:
          type: string
        idExpireDate:
          type: string
        birthday:
          type: string
          format: date
          example: 'YYYY-MM-DD, e.g. 2010-01-21'
        residentialAddress:
          $ref: '#/components/schemas/Address'
        sharholdingRatio:
          type: string
      required:
        - name
        - idNumber
        - idFrontImg
        - idBackImg
    Error:
      title: Error
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    Account-Info:
      title: Account-Info
      type: object
      description: ''
      properties:
        number:
          type: string
          description: Account number
        name:
          type: string
          description: Account name
        bankName:
          type: string
          description: Bank name
        branchCode:
          type: string
          description: Branch code
        swift:
          type: string
          description: Bank SWIFT code
        region:
          type: string
          description: 'Account region, two letter region code'
    Document:
      title: Document
      type: object
      properties:
        name:
          type: string
          description: Document name
        size:
          type: string
          description: Document size
        createTime:
          type: string
          format: date-time
          description: 'Document create time, UTC timestamp'
      required:
        - name
